[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_22"]

[phases.build]
cmds = ["rm -rf node_modules package-lock.json", "npm install", "composer install --no-dev --optimize-autoloader", "npm run build"]